[package]
name = "javy-demo"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }


[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["workoss"]


[workspace]
resolve = "2"
members = [
    "crates/wasi-worker",
]
exclude = []

[dependencies]
bytes = "1.1.0"

[workspace.dependencies]
bytes = "1.1.0"