[package]
name = "javy-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#wasmparser = "0.118.1"
#tokio = {version = "^1.33.0", features = ["full"]}
wasmtime = {version = "^16.0.0", features = ["component-model", "wat"]}
wasmtime-wasi = {version = "^16.0.0", features = ["preview2", "tokio"]}
