[package]
name = "javy-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
wasmparser = "0.118.1"
#tokio = {version = "^1.33.0", features = ["full"]}
wasmtime = { version = "16.0.0", features = ["component-model"] }
wasmtime-wasi = "16.0.0"
#tokio = { version = "^1.33", features = ["rt", "rt-multi-thread", "macros"] }
