[package]
name = "javy-demo"
description = "javy demo"
homepage = "https://www.workoss.com/"
documentation = "https://www.workoss.com/"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = [
    "js-demo",
    "wasi-worker"
]

[workspace.package]
version = "0.0.1"
authors = ["workoss"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ossworkere/javy-demo"

